name: handyman_provider_flutter
description: A new Flutter project.

publish_to: 'none'

version: 5.6.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^4.6.20
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  cached_network_image: ^3.2.1
  google_fonts: ^3.0.1
  html: ^0.15.0
  http: ^0.13.5
  intl: ^0.17.0
  url_launcher: ^6.1.5
  flutter_vector_icons: ^1.0.0

  #Firebase
  firebase_core: ^1.20.1
  firebase_crashlytics: ^2.8.7
  firebase_remote_config: ^2.0.14
  firebase_auth: ^3.6.3
  firebase_storage: ^10.3.5
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^3.4.4

  auto_size_text: 3.0.0
  flutter_custom_tabs: ^1.0.4
  dotted_border: 2.0.0+2

  #image:
  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  file_picker: ^5.0.1
  lottie: ^1.4.1

  # PAYMENTS
  flutter_stripe: ^4.0.0
  razorpay_flutter: ^1.3.2
  flutterwave_standard: ^1.0.4

  #notifications:
  onesignal_flutter: ^3.4.1

  #chart
  syncfusion_flutter_charts: ^20.2.44

  #map:
  geocoding: ^2.0.4

  flutter_html: ^3.0.0-alpha.3

  flutter_image_stack: ^0.0.6

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/
    - assets/lottie/

